all: false
dir: '{{.InterfaceDir}}/mocks'
filename: 'mock_gen.go'
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: mocks
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/cleitonmarx/symbiont/examples/todomailer/internal/domain:
    config:
      all: true
  github.com/cleitonmarx/symbiont/examples/todomailer/internal/usecases:
    config:
      all: true
