// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/cleitonmarx/symbiont/examples/todomailer/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailSender creates a new instance of MockEmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailSender {
	mock := &MockEmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailSender is an autogenerated mock type for the EmailSender type
type MockEmailSender struct {
	mock.Mock
}

type MockEmailSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailSender) EXPECT() *MockEmailSender_Expecter {
	return &MockEmailSender_Expecter{mock: &_m.Mock}
}

// SendEmail provides a mock function for the type MockEmailSender
func (_mock *MockEmailSender) SendEmail(ctx context.Context, to string, subject string, body string) (string, error) {
	ret := _mock.Called(ctx, to, subject, body)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, to, subject, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, to, subject, body)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, to, subject, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailSender_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type MockEmailSender_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - subject string
//   - body string
func (_e *MockEmailSender_Expecter) SendEmail(ctx interface{}, to interface{}, subject interface{}, body interface{}) *MockEmailSender_SendEmail_Call {
	return &MockEmailSender_SendEmail_Call{Call: _e.mock.On("SendEmail", ctx, to, subject, body)}
}

func (_c *MockEmailSender_SendEmail_Call) Run(run func(ctx context.Context, to string, subject string, body string)) *MockEmailSender_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEmailSender_SendEmail_Call) Return(s string, err error) *MockEmailSender_SendEmail_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEmailSender_SendEmail_Call) RunAndReturn(run func(ctx context.Context, to string, subject string, body string) (string, error)) *MockEmailSender_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTodoEventPublisher creates a new instance of MockTodoEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoEventPublisher {
	mock := &MockTodoEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoEventPublisher is an autogenerated mock type for the TodoEventPublisher type
type MockTodoEventPublisher struct {
	mock.Mock
}

type MockTodoEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoEventPublisher) EXPECT() *MockTodoEventPublisher_Expecter {
	return &MockTodoEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishEvent provides a mock function for the type MockTodoEventPublisher
func (_mock *MockTodoEventPublisher) PublishEvent(ctx context.Context, event domain.TodoEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TodoEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoEventPublisher_PublishEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishEvent'
type MockTodoEventPublisher_PublishEvent_Call struct {
	*mock.Call
}

// PublishEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.TodoEvent
func (_e *MockTodoEventPublisher_Expecter) PublishEvent(ctx interface{}, event interface{}) *MockTodoEventPublisher_PublishEvent_Call {
	return &MockTodoEventPublisher_PublishEvent_Call{Call: _e.mock.On("PublishEvent", ctx, event)}
}

func (_c *MockTodoEventPublisher_PublishEvent_Call) Run(run func(ctx context.Context, event domain.TodoEvent)) *MockTodoEventPublisher_PublishEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TodoEvent
		if args[1] != nil {
			arg1 = args[1].(domain.TodoEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoEventPublisher_PublishEvent_Call) Return(err error) *MockTodoEventPublisher_PublishEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoEventPublisher_PublishEvent_Call) RunAndReturn(run func(ctx context.Context, event domain.TodoEvent) error) *MockTodoEventPublisher_PublishEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBoardSummaryGenerator creates a new instance of MockBoardSummaryGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBoardSummaryGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBoardSummaryGenerator {
	mock := &MockBoardSummaryGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBoardSummaryGenerator is an autogenerated mock type for the BoardSummaryGenerator type
type MockBoardSummaryGenerator struct {
	mock.Mock
}

type MockBoardSummaryGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBoardSummaryGenerator) EXPECT() *MockBoardSummaryGenerator_Expecter {
	return &MockBoardSummaryGenerator_Expecter{mock: &_m.Mock}
}

// GenerateBoardSummary provides a mock function for the type MockBoardSummaryGenerator
func (_mock *MockBoardSummaryGenerator) GenerateBoardSummary(ctx context.Context, todos []domain.Todo) (domain.BoardSummary, error) {
	ret := _mock.Called(ctx, todos)

	if len(ret) == 0 {
		panic("no return value specified for GenerateBoardSummary")
	}

	var r0 domain.BoardSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.Todo) (domain.BoardSummary, error)); ok {
		return returnFunc(ctx, todos)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.Todo) domain.BoardSummary); ok {
		r0 = returnFunc(ctx, todos)
	} else {
		r0 = ret.Get(0).(domain.BoardSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.Todo) error); ok {
		r1 = returnFunc(ctx, todos)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoardSummaryGenerator_GenerateBoardSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateBoardSummary'
type MockBoardSummaryGenerator_GenerateBoardSummary_Call struct {
	*mock.Call
}

// GenerateBoardSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - todos []domain.Todo
func (_e *MockBoardSummaryGenerator_Expecter) GenerateBoardSummary(ctx interface{}, todos interface{}) *MockBoardSummaryGenerator_GenerateBoardSummary_Call {
	return &MockBoardSummaryGenerator_GenerateBoardSummary_Call{Call: _e.mock.On("GenerateBoardSummary", ctx, todos)}
}

func (_c *MockBoardSummaryGenerator_GenerateBoardSummary_Call) Run(run func(ctx context.Context, todos []domain.Todo)) *MockBoardSummaryGenerator_GenerateBoardSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.Todo
		if args[1] != nil {
			arg1 = args[1].([]domain.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBoardSummaryGenerator_GenerateBoardSummary_Call) Return(boardSummary domain.BoardSummary, err error) *MockBoardSummaryGenerator_GenerateBoardSummary_Call {
	_c.Call.Return(boardSummary, err)
	return _c
}

func (_c *MockBoardSummaryGenerator_GenerateBoardSummary_Call) RunAndReturn(run func(ctx context.Context, todos []domain.Todo) (domain.BoardSummary, error)) *MockBoardSummaryGenerator_GenerateBoardSummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBoardSummaryRepository creates a new instance of MockBoardSummaryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBoardSummaryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBoardSummaryRepository {
	mock := &MockBoardSummaryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBoardSummaryRepository is an autogenerated mock type for the BoardSummaryRepository type
type MockBoardSummaryRepository struct {
	mock.Mock
}

type MockBoardSummaryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBoardSummaryRepository) EXPECT() *MockBoardSummaryRepository_Expecter {
	return &MockBoardSummaryRepository_Expecter{mock: &_m.Mock}
}

// GetLatestSummary provides a mock function for the type MockBoardSummaryRepository
func (_mock *MockBoardSummaryRepository) GetLatestSummary(ctx context.Context) (domain.BoardSummary, bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSummary")
	}

	var r0 domain.BoardSummary
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (domain.BoardSummary, bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) domain.BoardSummary); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(domain.BoardSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBoardSummaryRepository_GetLatestSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestSummary'
type MockBoardSummaryRepository_GetLatestSummary_Call struct {
	*mock.Call
}

// GetLatestSummary is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBoardSummaryRepository_Expecter) GetLatestSummary(ctx interface{}) *MockBoardSummaryRepository_GetLatestSummary_Call {
	return &MockBoardSummaryRepository_GetLatestSummary_Call{Call: _e.mock.On("GetLatestSummary", ctx)}
}

func (_c *MockBoardSummaryRepository_GetLatestSummary_Call) Run(run func(ctx context.Context)) *MockBoardSummaryRepository_GetLatestSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBoardSummaryRepository_GetLatestSummary_Call) Return(boardSummary domain.BoardSummary, b bool, err error) *MockBoardSummaryRepository_GetLatestSummary_Call {
	_c.Call.Return(boardSummary, b, err)
	return _c
}

func (_c *MockBoardSummaryRepository_GetLatestSummary_Call) RunAndReturn(run func(ctx context.Context) (domain.BoardSummary, bool, error)) *MockBoardSummaryRepository_GetLatestSummary_Call {
	_c.Call.Return(run)
	return _c
}

// StoreSummary provides a mock function for the type MockBoardSummaryRepository
func (_mock *MockBoardSummaryRepository) StoreSummary(ctx context.Context, summary domain.BoardSummary) error {
	ret := _mock.Called(ctx, summary)

	if len(ret) == 0 {
		panic("no return value specified for StoreSummary")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.BoardSummary) error); ok {
		r0 = returnFunc(ctx, summary)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBoardSummaryRepository_StoreSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreSummary'
type MockBoardSummaryRepository_StoreSummary_Call struct {
	*mock.Call
}

// StoreSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - summary domain.BoardSummary
func (_e *MockBoardSummaryRepository_Expecter) StoreSummary(ctx interface{}, summary interface{}) *MockBoardSummaryRepository_StoreSummary_Call {
	return &MockBoardSummaryRepository_StoreSummary_Call{Call: _e.mock.On("StoreSummary", ctx, summary)}
}

func (_c *MockBoardSummaryRepository_StoreSummary_Call) Run(run func(ctx context.Context, summary domain.BoardSummary)) *MockBoardSummaryRepository_StoreSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.BoardSummary
		if args[1] != nil {
			arg1 = args[1].(domain.BoardSummary)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBoardSummaryRepository_StoreSummary_Call) Return(err error) *MockBoardSummaryRepository_StoreSummary_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBoardSummaryRepository_StoreSummary_Call) RunAndReturn(run func(ctx context.Context, summary domain.BoardSummary) error) *MockBoardSummaryRepository_StoreSummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTimeService creates a new instance of MockTimeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTimeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTimeService {
	mock := &MockTimeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTimeService is an autogenerated mock type for the TimeService type
type MockTimeService struct {
	mock.Mock
}

type MockTimeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTimeService) EXPECT() *MockTimeService_Expecter {
	return &MockTimeService_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type MockTimeService
func (_mock *MockTimeService) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockTimeService_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockTimeService_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockTimeService_Expecter) Now() *MockTimeService_Now_Call {
	return &MockTimeService_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockTimeService_Now_Call) Run(run func()) *MockTimeService_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTimeService_Now_Call) Return(time1 time.Time) *MockTimeService_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockTimeService_Now_Call) RunAndReturn(run func() time.Time) *MockTimeService_Now_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTodoRepository creates a new instance of MockTodoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoRepository {
	mock := &MockTodoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoRepository is an autogenerated mock type for the TodoRepository type
type MockTodoRepository struct {
	mock.Mock
}

type MockTodoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoRepository) EXPECT() *MockTodoRepository_Expecter {
	return &MockTodoRepository_Expecter{mock: &_m.Mock}
}

// CreateTodo provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) CreateTodo(ctx context.Context, todo domain.Todo) error {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Todo) error); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoRepository_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockTodoRepository_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - todo domain.Todo
func (_e *MockTodoRepository_Expecter) CreateTodo(ctx interface{}, todo interface{}) *MockTodoRepository_CreateTodo_Call {
	return &MockTodoRepository_CreateTodo_Call{Call: _e.mock.On("CreateTodo", ctx, todo)}
}

func (_c *MockTodoRepository_CreateTodo_Call) Run(run func(ctx context.Context, todo domain.Todo)) *MockTodoRepository_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Todo
		if args[1] != nil {
			arg1 = args[1].(domain.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepository_CreateTodo_Call) Return(err error) *MockTodoRepository_CreateTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoRepository_CreateTodo_Call) RunAndReturn(run func(ctx context.Context, todo domain.Todo) error) *MockTodoRepository_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodo provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) GetTodo(ctx context.Context, id uuid.UUID) (domain.Todo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTodo")
	}

	var r0 domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Todo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Todo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Todo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepository_GetTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodo'
type MockTodoRepository_GetTodo_Call struct {
	*mock.Call
}

// GetTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTodoRepository_Expecter) GetTodo(ctx interface{}, id interface{}) *MockTodoRepository_GetTodo_Call {
	return &MockTodoRepository_GetTodo_Call{Call: _e.mock.On("GetTodo", ctx, id)}
}

func (_c *MockTodoRepository_GetTodo_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTodoRepository_GetTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepository_GetTodo_Call) Return(todo domain.Todo, err error) *MockTodoRepository_GetTodo_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoRepository_GetTodo_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Todo, error)) *MockTodoRepository_GetTodo_Call {
	_c.Call.Return(run)
	return _c
}

// ListTodos provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) ListTodos(ctx context.Context, page int, pageSize int, opts ...domain.ListTodoOptions) ([]domain.Todo, bool, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, page, pageSize, opts)
	} else {
		tmpRet = _mock.Called(ctx, page, pageSize)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListTodos")
	}

	var r0 []domain.Todo
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, ...domain.ListTodoOptions) ([]domain.Todo, bool, error)); ok {
		return returnFunc(ctx, page, pageSize, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, ...domain.ListTodoOptions) []domain.Todo); ok {
		r0 = returnFunc(ctx, page, pageSize, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, ...domain.ListTodoOptions) bool); ok {
		r1 = returnFunc(ctx, page, pageSize, opts...)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int, ...domain.ListTodoOptions) error); ok {
		r2 = returnFunc(ctx, page, pageSize, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTodoRepository_ListTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTodos'
type MockTodoRepository_ListTodos_Call struct {
	*mock.Call
}

// ListTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
//   - opts ...domain.ListTodoOptions
func (_e *MockTodoRepository_Expecter) ListTodos(ctx interface{}, page interface{}, pageSize interface{}, opts ...interface{}) *MockTodoRepository_ListTodos_Call {
	return &MockTodoRepository_ListTodos_Call{Call: _e.mock.On("ListTodos",
		append([]interface{}{ctx, page, pageSize}, opts...)...)}
}

func (_c *MockTodoRepository_ListTodos_Call) Run(run func(ctx context.Context, page int, pageSize int, opts ...domain.ListTodoOptions)) *MockTodoRepository_ListTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []domain.ListTodoOptions
		var variadicArgs []domain.ListTodoOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]domain.ListTodoOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockTodoRepository_ListTodos_Call) Return(todos []domain.Todo, b bool, err error) *MockTodoRepository_ListTodos_Call {
	_c.Call.Return(todos, b, err)
	return _c
}

func (_c *MockTodoRepository_ListTodos_Call) RunAndReturn(run func(ctx context.Context, page int, pageSize int, opts ...domain.ListTodoOptions) ([]domain.Todo, bool, error)) *MockTodoRepository_ListTodos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) UpdateTodo(ctx context.Context, todo domain.Todo) error {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Todo) error); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoRepository_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockTodoRepository_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - todo domain.Todo
func (_e *MockTodoRepository_Expecter) UpdateTodo(ctx interface{}, todo interface{}) *MockTodoRepository_UpdateTodo_Call {
	return &MockTodoRepository_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, todo)}
}

func (_c *MockTodoRepository_UpdateTodo_Call) Run(run func(ctx context.Context, todo domain.Todo)) *MockTodoRepository_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Todo
		if args[1] != nil {
			arg1 = args[1].(domain.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepository_UpdateTodo_Call) Return(err error) *MockTodoRepository_UpdateTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoRepository_UpdateTodo_Call) RunAndReturn(run func(ctx context.Context, todo domain.Todo) error) *MockTodoRepository_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}
