// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/cleitonmarx/symbiont/examples/todoapp/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateTodo creates a new instance of MockCreateTodo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateTodo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateTodo {
	mock := &MockCreateTodo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateTodo is an autogenerated mock type for the CreateTodo type
type MockCreateTodo struct {
	mock.Mock
}

type MockCreateTodo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateTodo) EXPECT() *MockCreateTodo_Expecter {
	return &MockCreateTodo_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCreateTodo
func (_mock *MockCreateTodo) Execute(ctx context.Context, title string, dueDate time.Time) (domain.Todo, error) {
	ret := _mock.Called(ctx, title, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (domain.Todo, error)); ok {
		return returnFunc(ctx, title, dueDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) domain.Todo); ok {
		r0 = returnFunc(ctx, title, dueDate)
	} else {
		r0 = ret.Get(0).(domain.Todo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, title, dueDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateTodo_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateTodo_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - dueDate time.Time
func (_e *MockCreateTodo_Expecter) Execute(ctx interface{}, title interface{}, dueDate interface{}) *MockCreateTodo_Execute_Call {
	return &MockCreateTodo_Execute_Call{Call: _e.mock.On("Execute", ctx, title, dueDate)}
}

func (_c *MockCreateTodo_Execute_Call) Run(run func(ctx context.Context, title string, dueDate time.Time)) *MockCreateTodo_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCreateTodo_Execute_Call) Return(todo domain.Todo, err error) *MockCreateTodo_Execute_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockCreateTodo_Execute_Call) RunAndReturn(run func(ctx context.Context, title string, dueDate time.Time) (domain.Todo, error)) *MockCreateTodo_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerateBoardSummary creates a new instance of MockGenerateBoardSummary. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerateBoardSummary(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerateBoardSummary {
	mock := &MockGenerateBoardSummary{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenerateBoardSummary is an autogenerated mock type for the GenerateBoardSummary type
type MockGenerateBoardSummary struct {
	mock.Mock
}

type MockGenerateBoardSummary_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerateBoardSummary) EXPECT() *MockGenerateBoardSummary_Expecter {
	return &MockGenerateBoardSummary_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockGenerateBoardSummary
func (_mock *MockGenerateBoardSummary) Execute(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGenerateBoardSummary_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGenerateBoardSummary_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGenerateBoardSummary_Expecter) Execute(ctx interface{}) *MockGenerateBoardSummary_Execute_Call {
	return &MockGenerateBoardSummary_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockGenerateBoardSummary_Execute_Call) Run(run func(ctx context.Context)) *MockGenerateBoardSummary_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGenerateBoardSummary_Execute_Call) Return(err error) *MockGenerateBoardSummary_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGenerateBoardSummary_Execute_Call) RunAndReturn(run func(ctx context.Context) error) *MockGenerateBoardSummary_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetBoardSummary creates a new instance of MockGetBoardSummary. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetBoardSummary(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetBoardSummary {
	mock := &MockGetBoardSummary{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetBoardSummary is an autogenerated mock type for the GetBoardSummary type
type MockGetBoardSummary struct {
	mock.Mock
}

type MockGetBoardSummary_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetBoardSummary) EXPECT() *MockGetBoardSummary_Expecter {
	return &MockGetBoardSummary_Expecter{mock: &_m.Mock}
}

// Query provides a mock function for the type MockGetBoardSummary
func (_mock *MockGetBoardSummary) Query(ctx context.Context) (domain.BoardSummary, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 domain.BoardSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (domain.BoardSummary, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) domain.BoardSummary); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(domain.BoardSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetBoardSummary_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockGetBoardSummary_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGetBoardSummary_Expecter) Query(ctx interface{}) *MockGetBoardSummary_Query_Call {
	return &MockGetBoardSummary_Query_Call{Call: _e.mock.On("Query", ctx)}
}

func (_c *MockGetBoardSummary_Query_Call) Run(run func(ctx context.Context)) *MockGetBoardSummary_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGetBoardSummary_Query_Call) Return(boardSummary domain.BoardSummary, err error) *MockGetBoardSummary_Query_Call {
	_c.Call.Return(boardSummary, err)
	return _c
}

func (_c *MockGetBoardSummary_Query_Call) RunAndReturn(run func(ctx context.Context) (domain.BoardSummary, error)) *MockGetBoardSummary_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListTodos creates a new instance of MockListTodos. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListTodos(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListTodos {
	mock := &MockListTodos{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListTodos is an autogenerated mock type for the ListTodos type
type MockListTodos struct {
	mock.Mock
}

type MockListTodos_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListTodos) EXPECT() *MockListTodos_Expecter {
	return &MockListTodos_Expecter{mock: &_m.Mock}
}

// Query provides a mock function for the type MockListTodos
func (_mock *MockListTodos) Query(ctx context.Context, page int, pageSize int, opts ...domain.ListTodoOptions) ([]domain.Todo, bool, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, page, pageSize, opts)
	} else {
		tmpRet = _mock.Called(ctx, page, pageSize)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []domain.Todo
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, ...domain.ListTodoOptions) ([]domain.Todo, bool, error)); ok {
		return returnFunc(ctx, page, pageSize, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, ...domain.ListTodoOptions) []domain.Todo); ok {
		r0 = returnFunc(ctx, page, pageSize, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, ...domain.ListTodoOptions) bool); ok {
		r1 = returnFunc(ctx, page, pageSize, opts...)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int, ...domain.ListTodoOptions) error); ok {
		r2 = returnFunc(ctx, page, pageSize, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockListTodos_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockListTodos_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
//   - opts ...domain.ListTodoOptions
func (_e *MockListTodos_Expecter) Query(ctx interface{}, page interface{}, pageSize interface{}, opts ...interface{}) *MockListTodos_Query_Call {
	return &MockListTodos_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, page, pageSize}, opts...)...)}
}

func (_c *MockListTodos_Query_Call) Run(run func(ctx context.Context, page int, pageSize int, opts ...domain.ListTodoOptions)) *MockListTodos_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []domain.ListTodoOptions
		var variadicArgs []domain.ListTodoOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]domain.ListTodoOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockListTodos_Query_Call) Return(todos []domain.Todo, b bool, err error) *MockListTodos_Query_Call {
	_c.Call.Return(todos, b, err)
	return _c
}

func (_c *MockListTodos_Query_Call) RunAndReturn(run func(ctx context.Context, page int, pageSize int, opts ...domain.ListTodoOptions) ([]domain.Todo, bool, error)) *MockListTodos_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateTodo creates a new instance of MockUpdateTodo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateTodo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateTodo {
	mock := &MockUpdateTodo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateTodo is an autogenerated mock type for the UpdateTodo type
type MockUpdateTodo struct {
	mock.Mock
}

type MockUpdateTodo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateTodo) EXPECT() *MockUpdateTodo_Expecter {
	return &MockUpdateTodo_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockUpdateTodo
func (_mock *MockUpdateTodo) Execute(ctx context.Context, id uuid.UUID, title *string, status *domain.TodoStatus, dueDate *time.Time) (domain.Todo, error) {
	ret := _mock.Called(ctx, id, title, status, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *domain.TodoStatus, *time.Time) (domain.Todo, error)); ok {
		return returnFunc(ctx, id, title, status, dueDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *domain.TodoStatus, *time.Time) domain.Todo); ok {
		r0 = returnFunc(ctx, id, title, status, dueDate)
	} else {
		r0 = ret.Get(0).(domain.Todo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *string, *domain.TodoStatus, *time.Time) error); ok {
		r1 = returnFunc(ctx, id, title, status, dueDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateTodo_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateTodo_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - title *string
//   - status *domain.TodoStatus
//   - dueDate *time.Time
func (_e *MockUpdateTodo_Expecter) Execute(ctx interface{}, id interface{}, title interface{}, status interface{}, dueDate interface{}) *MockUpdateTodo_Execute_Call {
	return &MockUpdateTodo_Execute_Call{Call: _e.mock.On("Execute", ctx, id, title, status, dueDate)}
}

func (_c *MockUpdateTodo_Execute_Call) Run(run func(ctx context.Context, id uuid.UUID, title *string, status *domain.TodoStatus, dueDate *time.Time)) *MockUpdateTodo_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *domain.TodoStatus
		if args[3] != nil {
			arg3 = args[3].(*domain.TodoStatus)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUpdateTodo_Execute_Call) Return(todo domain.Todo, err error) *MockUpdateTodo_Execute_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockUpdateTodo_Execute_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, title *string, status *domain.TodoStatus, dueDate *time.Time) (domain.Todo, error)) *MockUpdateTodo_Execute_Call {
	_c.Call.Return(run)
	return _c
}
